import type { LogActivity } from '~~/app/types'

export default defineEventHandler((): LogActivity[] => {
    return [
        {
            id: 1,
            category: 'login',
            text: 'Successful Login Attempt',
            description: 'You successfully logged in from a recognized device.',
            datetime: 'September 09, 2026 at 08:10 AM',
            icon: 'i-lucide-log-in',
            color: 'text-success',
            bg: 'bg-success/10',
        },
        {
            id: 2,
            category: 'leave',
            text: 'Successfully Applied Leave Request',
            description: 'Your leave request has been submitted and is pending approval.',
            datetime: 'September 08, 2026 at 08:48 AM',
            icon: 'i-lucide-calendar-check',
            color: 'text-primary',
            bg: 'bg-primary/10',
        },
        {
            id: 3,
            category: 'overtime',
            text: 'Overtime Request Approved',
            description: 'Your overtime request for September 5 has been approved.',
            datetime: 'September 06, 2026 at 02:15 PM',
            icon: 'i-lucide-clock-4',
            color: 'text-success',
            bg: 'bg-success/10',
        },
        {
            id: 4,
            category: 'time',
            text: 'Successfully timed out.',
            description: 'You clocked out at 05:02 PM on September 05, 2026.',
            datetime: 'September 05, 2026 at 05:02 PM',
            icon: 'i-lucide-zap-off',
            color: 'text-orange-500',
            bg: 'bg-orange-500/10',
        },
        {
            id: 5,
            category: 'time',
            text: 'Successfully timed in.',
            description: 'You clocked in at 07:10 AM on September 05, 2026.',
            datetime: 'September 05, 2026 at 07:10 AM',
            icon: 'i-lucide-zap',
            color: 'text-primary',
            bg: 'bg-primary/10',
        },
        {
            id: 6,
            category: 'system',
            text: 'Password Changed Successfully',
            description: 'Your account password was updated.',
            datetime: 'September 02, 2026 at 11:30 AM',
            icon: 'i-lucide-shield-check',
            color: 'text-success',
            bg: 'bg-success/10',
        },
        {
            id: 7,
            category: 'profile',
            text: 'Profile Information Updated',
            description: 'You updated your contact number.',
            datetime: 'August 28, 2026 at 04:20 PM',
            icon: 'i-lucide-user',
            color: 'text-primary',
            bg: 'bg-primary/10',
        },
        {
            id: 8,
            category: 'time',
            text: 'Successfully timed out.',
            description: 'You clocked out at 06:15 PM on August 25, 2026.',
            datetime: 'August 25, 2026 at 06:15 PM',
            icon: 'i-lucide-zap-off',
            color: 'text-orange-500',
            bg: 'bg-orange-500/10',
        },
    ]
})
