import type { Asset } from '~/types'

export default eventHandler(async () => {
    const assets: Asset[] = [
        {
            id: 1,
            assetTag: '11002X120124216',
            name: 'Rapoo NK1800 Wired Keyboard',
            category: 'Keyboards',
            brandModel: 'Rapoo NK1800',
            purchased: '08/06/2026',
            cost: 499.00,
            status: 'AVAILABLE',
            location: 'Workspace Area',
        },
        {
            id: 2,
            assetTag: 'C07HN0R6Q6NV',
            name: 'Apple Mac Mini (M1, 2020)',
            category: 'Desktop Computers',
            brandModel: 'Apple Mac Mini (M1, 2020)',
            purchased: '09/09/2025',
            cost: 39990.00,
            status: 'AVAILABLE',
            location: 'Workspace Area',
        },
        {
            id: 3,
            assetTag: 'C07FQ081Q6NV',
            name: 'Apple Mac Mini (2020)',
            category: 'Desktop Computers',
            brandModel: 'Apple Mac Mini (M1, 2020)',
            purchased: '07/23/2026',
            cost: 39990.00,
            status: 'ASSIGNED',
            location: 'Workspace Area',
        },
        {
            id: 4,
            assetTag: 'A4702X120102421',
            name: 'Rapoo NK1800 Wired Keyboard',
            category: 'Keyboards',
            brandModel: 'Rapoo NK1800',
            purchased: '07/23/2026',
            cost: 499.00,
            status: 'ASSIGNED',
            location: 'Workspace Area',
        },
        {
            id: 5,
            assetTag: 'PB9H184703490',
            name: 'MSI PRO MP223 E2 Monitor',
            category: 'Monitors',
            brandModel: 'MSI PRO MP223 E2',
            purchased: '07/23/2026',
            cost: 3990.00,
            status: 'ASSIGNED',
            location: 'Workspace Area',
        },
        {
            id: 6,
            assetTag: 'A4702X120102425',
            name: 'Rapoo N200 Wired Optical Mouse',
            category: 'Mouse',
            brandModel: 'Rapoo N200',
            purchased: '07/23/2026',
            cost: 300.00,
            status: 'ASSIGNED',
            location: 'UI/UX Room',
        },
        {
            id: 7,
            assetTag: 'C07FQ095Q6NV',
            name: 'Apple Mac Mini (2020)',
            category: 'Desktop Computers',
            brandModel: 'Apple Mac Mini (M1, 2020)',
            purchased: '07/23/2026',
            cost: 39990.00,
            status: 'ASSIGNED',
            location: 'UI/UX Room',
        },
        {
            id: 8,
            assetTag: 'PE220300',
            name: 'A4Tech KK-3 Keyboard',
            category: 'Keyboards',
            brandModel: 'A4Tech KK-3',
            purchased: '07/23/2026',
            cost: 450.00,
            status: 'ASSIGNED',
            location: 'UI/UX Room',
        },
        {
            id: 9,
            assetTag: 'URHHZFC2',
            name: 'Lenovo D27-30 Monitor',
            category: 'Monitors',
            brandModel: 'Lenovo D27-30',
            purchased: '07/23/2026',
            cost: 9000.00,
            status: 'ASSIGNED',
            location: 'UI/UX Room',
        },
        {
            id: 10,
            assetTag: '5CD4256C48',
            name: 'HP Laptop 15s-eq2xxx',
            category: 'Laptop Computers',
            brandModel: 'HP Laptop 15s-eq2xxx',
            purchased: '07/15/2026',
            cost: 32990.00,
            status: 'ASSIGNED',
            location: 'UI/UX Room',
        },
        {
            id: 11,
            assetTag: 'B6Y8U0V2',
            name: 'Logitech MX Master 3S',
            category: 'Mouse',
            brandModel: 'Logitech MX Master 3S',
            purchased: '01/10/2026',
            cost: 5500.00,
            status: 'AVAILABLE',
            location: 'IT Storage',
        },
        {
            id: 12,
            assetTag: 'H1K9L4M2',
            name: 'Dell UltraSharp 27 Monitor',
            category: 'Monitors',
            brandModel: 'Dell U2723QE',
            purchased: '11/05/2025',
            cost: 35000.00,
            status: 'UNDER REPAIR',
            location: 'IT Storage',
        },
        {
            id: 13,
            assetTag: 'P0O9I8U7',
            name: 'MacBook Pro 16" (M3 Max)',
            category: 'Laptop Computers',
            brandModel: 'Apple MacBook Pro',
            purchased: '12/20/2025',
            cost: 180000.00,
            status: 'ASSIGNED',
            location: 'Executive Office',
        },
        {
            id: 14,
            assetTag: 'Q1W2E3R4',
            name: 'Keychron K8 Pro Keyboard',
            category: 'Keyboards',
            brandModel: 'Keychron K8 Pro',
            purchased: '02/14/2026',
            cost: 6500.00,
            status: 'ASSIGNED',
            location: 'Workspace Area',
        },
        {
            id: 15,
            assetTag: 'T5Y6U7I8',
            name: 'ErgoCentric Office Chair',
            category: 'Office Furniture',
            brandModel: 'ErgoCentric tCentric',
            purchased: '03/01/2024',
            cost: 15000.00,
            status: 'RETIRED',
            location: 'Workspace Area',
        },
    ]

    return {
        assets
    }
})
