import type { LogActivity } from '~~/app/types'

export default defineEventHandler((): LogActivity[] => {
    return [
        {
            id: 1,
            category: 'time',
            text: 'Successfully timed in.',
            description: 'You clocked in at 07:10 AM on September 04, 2026.',
            datetime: 'September 04, 2026 at 07:10 AM',
            icon: 'i-lucide-zap',
            color: 'text-primary',
            bg: 'bg-primary/10',
            unread: true,
        },
        {
            id: 2,
            category: 'approval',
            text: 'Approved Leave Request',
            description: 'Your leave request for SURRIGA, JOSEPH EBRON was approved.',
            datetime: 'September 04, 2026 at 02:15 PM',
            icon: 'i-lucide-check-circle',
            color: 'text-success',
            bg: 'bg-success/10',
            unread: true,
        },
        {
            id: 3,
            category: 'login',
            text: 'Successful Login Attempt',
            description: 'You successfully logged in from a recognized device.',
            datetime: 'September 01, 2026 at 08:33 AM',
            icon: 'i-lucide-log-in',
            color: 'text-success',
            bg: 'bg-success/10',
            unread: false,
        },
        {
            id: 4,
            category: 'time',
            text: 'Successfully timed in.',
            description: 'You clocked in at 07:21 AM on August 28, 2026.',
            datetime: 'August 28, 2026 at 07:21 AM',
            icon: 'i-lucide-zap',
            color: 'text-primary',
            bg: 'bg-primary/10',
            unread: false,
        },
        {
            id: 5,
            category: 'login',
            text: 'Successful Login Attempt',
            description: 'You successfully logged in from a recognized device.',
            datetime: 'August 28, 2026 at 10:11 AM',
            icon: 'i-lucide-log-in',
            color: 'text-success',
            bg: 'bg-success/10',
            unread: false,
        },
        {
            id: 6,
            category: 'leave',
            text: 'Successfully Applied Leave Request',
            description: 'Your leave request has been submitted and is pending approval.',
            datetime: 'August 17, 2026 at 09:16 AM',
            icon: 'i-lucide-calendar-check',
            color: 'text-primary',
            bg: 'bg-primary/10',
            unread: false,
        },
        {
            id: 7,
            category: 'overtime',
            text: 'Approved Overtime Request',
            description: 'Your overtime request for August 15, 2026 has been approved.',
            datetime: 'August 16, 2026 at 11:20 AM',
            icon: 'i-lucide-clock-4',
            color: 'text-success',
            bg: 'bg-success/10',
            unread: false,
        },
        {
            id: 8,
            category: 'time',
            text: 'Successfully timed out.',
            description: 'You clocked out at 05:01 PM on August 15, 2026.',
            datetime: 'August 15, 2026 at 05:01 PM',
            icon: 'i-lucide-zap-off',
            color: 'text-orange-500',
            bg: 'bg-orange-500/10',
            unread: false,
        },
        {
            id: 9,
            category: 'profile',
            text: 'Profile Updated',
            description: 'You successfully updated your profile picture.',
            datetime: 'August 10, 2026 at 03:45 PM',
            icon: 'i-lucide-user',
            color: 'text-primary',
            bg: 'bg-primary/10',
            unread: false,
        },
        {
            id: 10,
            category: 'system',
            text: 'System Maintenance Scheduled',
            description: 'The HRIS will undergo maintenance on August 12, 2026.',
            datetime: 'August 08, 2026 at 09:00 AM',
            icon: 'i-lucide-settings',
            color: 'text-gray-500',
            bg: 'bg-gray-500/10',
            unread: false,
        }
    ]
})
